# Generated by Django 3.2.16 on 2022-11-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(null=True, verbose_name='Nav Snapshot Date')),
                ('total_expected_shareclass', models.IntegerField(null=True, verbose_name='Total Expected Number Of Shareclass')),
                ('pending_shareclass', models.IntegerField(null=True, verbose_name='Total Pending Number Of Shareclass')),
                ('record_insert_datetime', models.DateTimeField(null=True, verbose_name='Record Inserted Date and Time')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Backlog Daily Navs',
            },
        ),
    ]
