# Generated by Django 3.2.16 on 2022-11-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_delete_job_profidsafafles'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_profilesssssss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companey_name', models.CharField(default='', max_length=100, verbose_name='Job_industries')),
                ('job_Title', models.CharField(default='', max_length=100)),
                ('job_type', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
