# Generated by Django 3.2.16 on 2022-11-14 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_alter_job_industries_updated_by_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_industriesd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='Job_industries')),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Temp Updated By')),
            ],
            options={
                'verbose_name_plural': 'Job_industries',
            },
        ),
    ]
