# Generated by Django 3.2.16 on 2022-11-15 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20221115_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_profiles',
            name='status',
        ),
    ]
