# Generated by Django 3.2.16 on 2022-11-16 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_job_profidsafafles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='job_profidsafafles',
        ),
    ]
