# Generated by Django 3.2.16 on 2022-11-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_job_profiles_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_profiles',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
