# Generated by Django 3.2.16 on 2022-11-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_job_profiles_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_profiles',
            name='companey_name',
            field=models.CharField(default='NULL', max_length=100, verbose_name='Job_industries'),
        ),
        migrations.AlterField(
            model_name='job_profiles',
            name='country',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job_profiles',
            name='job_Category',
            field=models.CharField(default='NULL', max_length=1000),
        ),
        migrations.AlterField(
            model_name='job_profiles',
            name='job_Title',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='job_profiles',
            name='job_type',
            field=models.CharField(default='NULL', max_length=1000),
        ),
    ]
