# Generated by Django 3.2.16 on 2022-11-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20221115_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_profiles',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job_profiles',
            name='job_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='job_profiles',
            name='mobile_no',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='job_profiles',
            name='companey_name',
            field=models.CharField(default='', max_length=100, verbose_name='Job_industries'),
        ),
        migrations.AlterField(
            model_name='job_profiles',
            name='job_Category',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='job_profiles',
            name='job_Title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='job_profiles',
            name='job_type',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
